name: CI-CD to EC2 via ECR

on:
  push:
    branches: ["main"]

jobs:
  build-test-push-deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
      IMAGE_TAG: ${{ github.sha }}

      # Test envs (mocked)
      APP_NAME: llm_fastapi
      ENV: test
      MODEL_ID: dummy
      MAXTOKEN: 10
      TEMPERATURE: 0.1
      TOPP: 0.9
      JWT_SECRET: test-secret
      JWT_ALGORITHM: HS256
      JWT_EXPIRE_MINUTES: 60
      AUTH_USERNAME: admin
      AUTH_PASSWORD: admin123

    steps:
    # -------------------------------
    # 1. CHECKOUT
    # -------------------------------
    - uses: actions/checkout@v4

    # -------------------------------
    # 2. TESTS
    # -------------------------------
    - uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)
        pytest -q

    # -------------------------------
    # 3. AWS AUTH
    # -------------------------------
    - uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password --region $AWS_REGION \
        | docker login --username AWS \
          --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

    # -------------------------------
    # 4. BUILD + PUSH
    # -------------------------------
    - name: Build Docker image
      run: |
        docker build -t $ECR_REPOSITORY:$IMAGE_TAG .

    - name: Tag image
      run: |
        docker tag $ECR_REPOSITORY:$IMAGE_TAG \
        $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG

    - name: Push image
      run: |
        docker push \
        $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG

    # -------------------------------
    # 5. DEPLOY TO EC2
    # -------------------------------
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          set -e

          aws ecr get-login-password --region $AWS_REGION \
          | docker login --username AWS \
            --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

          cd ~/Chatbot-backend-AWS

          export IMAGE_TAG=${{ github.sha }}

          docker compose down
          docker compose pull
          docker compose up -d
